<a href="https://colab.research.google.com/github/Saeswar/AI-ML-AVANTHI-SAESWAR/blob/main/Day_4_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

pip install numpy


In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
#shape
b.shape

(2, 3)

In [ ]:
b.dtype



dtype('float64')

In [ ]:
a.nbytes

24

ACCESING /CHANGING

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a[1,5]

13

initializing arrays

In [54]:
x=np.ones((1,5,5),dtype='int32')