<a href="https://colab.research.google.com/github/Saeswar/AI-ML-AVANTHI-SAESWAR/blob/main/problems_py_day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

memmory size of array

In [ ]:
a = np.array([1,2,3,4,5,6])
a.nbytes

48

create a null veactor of size 10 but the 5 th values which is 1

In [ ]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

create a vector  with value ranging from 10 to *49*

In [ ]:
np.random.randint(10,49, size=(10))

array([41, 21, 17, 19, 15, 48, 41, 46, 38, 25])

In [ ]:
a=np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

reverse vector (first element become last)

In [ ]:
a=np.array([13,4,31,23,17,12,9,7])
a[::-1]
a


array([13,  4, 31, 23, 17, 12,  9,  7])

create a 3x3 matrix with values ranging from 0 to 8

NameError: name 'np' is not defined